version: '3.8'
services:
  postgres:
    image: postgres:latest
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    networks:
      - mynetwork
    

    
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgres://user:password@postgres/mydatabase
    ports:
      - 8000:8000
    depends_on:
      - postgres
    networks:
      - mynetwork

networks:
  mynetwork:
    
volumes:
  postgres_data:
